import React from 'react';
import { 
  Cpu, Server, Laptop, Database, Shield, Lock, 
  ArrowDown, CheckCircle, Terminal, HelpCircle 
} from 'lucide-react';

export default function ArchitecturePage() {
  const vivaTerms = [
    {
      term: 'WebAuthn (W3C Standard)',
      def: 'A browser-based API allowing web applications to create and verify strong public-key credentials. Part of FIDO2.'
    },
    {
      term: 'Passkeys',
      def: 'Discoverable FIDO2 credentials synced across user devices or stored in hardware authenticators, replacing passwords.'
    },
    {
      term: 'FIDO2 (Fast Identity Online)',
      def: 'The overarching standard composed of W3C WebAuthn (browser-to-server) and CTAP2 (authenticator-to-client).'
    },
    {
      term: 'Public-Key Cryptography',
      def: 'Asymmetric mathematics where data signed with an unshared private key is verified with an openly known public key.'
    },
    {
      term: 'Digital Signatures',
      def: 'Mathematical schemes (ECDSA/EdDSA) ensuring authenticity, integrity, and non-repudiation of client assertions.'
    },
    {
      term: 'Challenge-Response Nonce',
      def: 'A random 32-byte number generated by the server for each login. Prevents replay attacks by expiring after single use.'
    },
    {
      term: 'Relying Party (RP)',
      def: 'The web application backend (this server) that requests WebAuthn authentication and verifies client assertions.'
    },
    {
      term: 'Authenticator',
      def: 'Hardware/software entity that manages private keys and signs challenges (e.g. Touch ID, Windows Hello, YubiKey).'
    },
    {
      term: 'Credential ID',
      def: 'A globally unique byte sequence generated during registration that identifies which public key the server should retrieve.'
    },
    {
      term: 'RP ID (Relying Party ID)',
      def: 'The effective domain name (e.g. "localhost" or "example.com") bound to the passkey. Ensures phishing resistance.'
    },
    {
      term: 'Origin',
      def: 'The full URL scheme, host, and port (e.g. http://localhost:5173) verified by the server to prevent cross-origin forgery.'
    },
    {
      term: 'Sign Counter (Clone Detection)',
      def: 'A monotonically increasing number in authenticator data. If a cloned key authenticates, counter anomaly detects the threat.'
    },
    {
      term: 'User Verification (UV)',
      def: 'Local test proving the genuine user is present (biometric fingerprint/face scan or device PIN) before releasing signatures.'
    }
  ];

  return (
    <div style={{ maxWidth: '1100px', margin: '0 auto' }}>
      <div style={{ textAlign: 'center', marginBottom: '3rem' }}>
        <div style={{ display: 'inline-flex', marginBottom: '0.75rem' }}>
          <span className="badge badge-cyan">
            <Cpu size={14} />
            System Design & Engineering Specifications
          </span>
        </div>
        <h1 style={{ fontSize: '2.5rem', marginBottom: '0.75rem' }}>
          System Architecture & Viva Technical Reference
        </h1>
        <p style={{ color: 'var(--text-secondary)', fontSize: '1.1rem', maxWidth: '750px', margin: '0 auto' }}>
          Comprehensive architectural blueprint, data-flow pipeline, and academic definitions 
          tailored for final-year engineering defense and viva questions.
        </p>
      </div>

      {/* 1. ARCHITECTURE DIAGRAM (Section 16) */}
      <section className="cyber-card" style={{ padding: '2.5rem', marginBottom: '3rem', border: '1px solid var(--border-glow)' }}>
        <h2 style={{ fontSize: '1.4rem', textAlign: 'center', marginBottom: '2rem', textTransform: 'uppercase', letterSpacing: '0.05em' }}>
          End-to-End System Architecture
        </h2>

        <div style={{
          maxWidth: '550px',
          margin: '0 auto',
          display: 'flex',
          flexDirection: 'column',
          alignItems: 'center',
          gap: '0.5rem'
        }}>
          {/* Node 1: User */}
          <div style={{
            width: '100%',
            background: 'rgba(8, 14, 28, 0.8)',
            border: '1px solid var(--border-subtle)',
            borderRadius: 'var(--radius-sm)',
            padding: '1.25rem',
            textAlign: 'center'
          }}>
            <div style={{ fontWeight: 800, fontSize: '1.1rem', color: 'var(--text-primary)' }}>USER</div>
            <div style={{ fontSize: '0.8rem', color: 'var(--text-muted)' }}>Initiates registration / authentication flow</div>
          </div>

          <ArrowDown size={22} color="var(--cyan-neon)" />

          {/* Node 2: Browser */}
          <div style={{
            width: '100%',
            background: 'rgba(0, 240, 255, 0.08)',
            border: '1px solid var(--border-glow)',
            borderRadius: 'var(--radius-sm)',
            padding: '1.25rem',
            textAlign: 'center'
          }}>
            <div style={{ fontWeight: 800, fontSize: '1.1rem', color: 'var(--cyan-neon)' }}>BROWSER CLIENT</div>
            <div style={{ fontSize: '0.85rem', color: 'var(--text-primary)', marginTop: '0.2rem' }}>W3C WebAuthn API (Level 3)</div>
            <div style={{ fontSize: '0.78rem', color: 'var(--text-muted)' }}>navigator.credentials.create() &amp; get()</div>
          </div>

          <ArrowDown size={22} color="var(--emerald-neon)" />

          {/* Node 3: Authenticator */}
          <div style={{
            width: '100%',
            background: 'rgba(0, 230, 118, 0.08)',
            border: '1px solid var(--border-emerald)',
            borderRadius: 'var(--radius-sm)',
            padding: '1.25rem',
            textAlign: 'center'
          }}>
            <div style={{ fontWeight: 800, fontSize: '1.1rem', color: 'var(--emerald-neon)' }}>AUTHENTICATOR</div>
            <div style={{ fontSize: '0.85rem', color: 'var(--text-primary)', marginTop: '0.2rem' }}>Fingerprint / Face / PIN (Secure Enclave / TPM)</div>
            <div style={{ fontSize: '0.78rem', color: 'var(--text-muted)' }}>Private Key Protection &amp; ECDSA P-256 Signing</div>
          </div>

          <div style={{ fontSize: '0.8rem', color: 'var(--purple-neon)', fontWeight: 600, padding: '0.2rem 0' }}>
            ↓ Cryptographic Assertion (Digital Signature) ↓
          </div>

          {/* Node 4: Backend */}
          <div style={{
            width: '100%',
            background: 'rgba(157, 78, 221, 0.08)',
            border: '1px solid rgba(157, 78, 221, 0.4)',
            borderRadius: 'var(--radius-sm)',
            padding: '1.25rem',
            textAlign: 'center'
          }}>
            <div style={{ fontWeight: 800, fontSize: '1.1rem', color: '#c77dff' }}>BACKEND (FASTAPI)</div>
            <div style={{ fontSize: '0.85rem', color: 'var(--text-primary)', marginTop: '0.2rem' }}>PyWebAuthn Verification Engine</div>
            <div style={{ fontSize: '0.78rem', color: 'var(--text-muted)' }}>Challenge Validation, Origin Binding, &amp; Signature Check</div>
          </div>

          <ArrowDown size={22} color="var(--cyan-neon)" />

          {/* Node 5: Database */}
          <div style={{
            width: '100%',
            background: 'rgba(8, 14, 28, 0.8)',
            border: '1px solid var(--border-subtle)',
            borderRadius: 'var(--radius-sm)',
            padding: '1.25rem',
            textAlign: 'center'
          }}>
            <div style={{ fontWeight: 800, fontSize: '1.1rem', color: 'var(--text-primary)' }}>DATABASE (SQLITE + SQLALCHEMY)</div>
            <div style={{ fontSize: '0.85rem', color: 'var(--cyan-neon)', marginTop: '0.2rem' }}>User | Credential ID | Public Key | Sign Counter</div>
            <div style={{ fontSize: '0.78rem', color: 'var(--emerald-neon)', fontWeight: 600, marginTop: '0.2rem' }}>
              STRICT ZERO PASSWORD COLUMNS
            </div>
          </div>
        </div>
      </section>

      {/* 2. TECHNICAL DETAILS FOR VIVA (Section 17) */}
      <section style={{ marginBottom: '3rem' }}>
        <h2 style={{ fontSize: '1.8rem', marginBottom: '1.75rem', textAlign: 'center' }}>
          Technical Terms &amp; Viva Examination Guide
        </h2>

        <div className="grid-2">
          {vivaTerms.map((item, idx) => (
            <div key={idx} className="cyber-card" style={{ padding: '1.5rem' }}>
              <div style={{
                fontSize: '1.05rem',
                fontWeight: 700,
                color: 'var(--cyan-neon)',
                marginBottom: '0.4rem',
                display: 'flex',
                alignItems: 'center',
                gap: '0.5rem'
              }}>
                <CheckCircle size={16} color="var(--emerald-neon)" />
                {item.term}
              </div>
              <p style={{ color: 'var(--text-secondary)', fontSize: '0.9rem', lineHeight: 1.5 }}>
                {item.def}
              </p>
            </div>
          ))}
        </div>
      </section>
    </div>
  );
}
